---
baseURL: https://jesusfj710.github.io/
paginate: 5
theme: PaperMod
copyright: ğŸ’šğŸ¤ğŸ’š -
keywords: ["blog", "website", "portfolio"]
author:
  name: JesÃºs FernÃ¡ndez JimÃ©nez
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  tag: tags

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
